config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root 'home#index'
  resources :home, only: [:show, :index]
  resources :restaurants
  resources :items, only: [:index, :show]
  resources :carts, only: :index
  resources :cart_items, only: [:create, :destroy] do
  post 'order', on: :collection
  # member do
  #   post :order
  # end
 end 
resources :orders, only: [:index, :new, :show, :destroy, :create]
  get '/search', to: 'home#search'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, Home
      end
    else
      can :read, Home
    end
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  # belongs_to :user
  # has_many :cart_items, dependent: :destroy
  # validates :total_amount, numericality: { grater_than: 0 }
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  before_save :set_total

  private

  def set_total
    self.total = item.price * quantity
  end

end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :restaurant
  belongs_to :item_category, class_name: 'ItemCategory'
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items, dependent: :destroy
  validates :name, :description, :price, presence: true
  validates :description, length: { maximum: 500, too_long: '%<count>s characters is the maximum allowed' }            
  validates :price, numericality: { grater_than: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/item_category.rb
# frozen_string_literal: true

class ItemCategory < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  before_save :set_sub_total

  private
  def set_sub_total
    self.sub_total=item.price*quantity 
  end
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, :description,:address,:phone_1,:phone_2,:minimum_order,:delivery_charge,presence: true
  validates :phone_1, :phone_2, numericality: { only_integer: true }
  validates :phone_1, :phone_2,length: {is: 10}
  validates :description, length: { maximum: 500, too_long: '%<count>s characters is the maximum allowed' }
  validates :minimum_order, numericality: { grater_than: 0 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :validatable
  
  after_validation :normalize_name, on: :create
  after_create :send_welcome_mail
  
  has_many :orders
  has_many :cart_items, dependent: :destroy
  validates :first_name,:last_name,:phone_number, presence: true
  validates :phone_number, numericality: { only_integer: true }
  validates :phone_number,length: {is: 10}
  def normalize_name
    self.first_name = first_name.titleize unless first_name.nil?
  end

  def send_welcome_mail
    UserMailer.welcome_mail(self).deliver_now
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def index
    @cartItems = current_user.cart_items
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController

  def search
    item_id = params[:item_id]
    restaurant_id = params[:restaurant_id]
    @results = if item_id.present? && restaurant_id.present?
                 Restaurant.includes(:items).where(id: restaurant_id, items: { id: item_id })
               elsif item_id.present?
                 Item.includes(:restaurant).where(id: item_id).map(&:restaurant)
               elsif restaurant_id.present?
                 Restaurant.includes(:items).where(id: restaurant_id)
               else
                 Restaurant.includes(:items).all
               end
  end

  def show
    @item = Item.find(params[:item_id]) unless params[:item_id].blank?
  end

end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :authenticate_user!
  def index
  @items=Item.all
  end

  def show
    @item=Item.find( params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/buildings_helper.rb
# frozen_string_literal: true

module BuildingsHelper
end

app/helpers/card_helper.rb
# frozen_string_literal: true

module CardHelper
end

app/helpers/cart_items_helper.rb
# frozen_string_literal: true

module CartItemsHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/carts/index.html.erb
<h1> "Cart Items" </h1>
<%if @cartItems.empty?%>
  <h2>Your cart is empty!!</h2>
<%else%>
<% @cartItems.each do |cartitem|%>

    <ul>
      <li><%= cartitem.item.name %></li>
      <li><%= cartitem.quantity %></li>
      <li><%=cartitem.total%></li>
      <p><%= button_to 'Remove', cart_item_path(cartitem), 
                                method: :delete,
                                data: { confirm: "are you sure, want to delete this item?"},
                                turbo: false %></p>
 <%end%>
    <h4>Total Price: <%=@cartItems.pluck(:total).inject(:+)%></h4>
  <%= button_to "order", order_cart_items_path(cart_item_id: @cartItems.first), method: :post %>
  </ul>
<%end%>
<table>
<th><%= button_to "Home", root_path, method: :get%> </th>
<th><%= button_to "Your Order", orders_path, method: :get%> </th>
</table>

app/views/items/index.html.erb
<h1>All Items</h1>

<table>
<thead>
    <tr>
      <th>Item Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description%></td>
        <td><%= item.price%></td>
        <td><%= link_to "Show", item %>  </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<p><%= @item.description %></p>
<p><%= @item.price %></p>

<%= form_with(url: cart_items_path, method: :post) do |form| %>
  <%= form.hidden_field :item_id, value: @item.id %>
  <%= button_to "Add to Cart", cart_items_path, params: {item: @item} %>
<% end %>