config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root 'home#index'
  resources :home, only: [:show, :index]
  resources :restaurants
  resources :items, only: [:index, :show]
  resources :carts, only: :index
  resources :cart_items, only: [:create, :destroy] do
  post 'order', on: :collection
  # member do
  #   post :order
  # end
 end 
resources :orders, only: [:index, :new, :show, :destroy, :create]
  get '/search', to: 'home#search'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.present?
      if user.has_role? :admin
        can :manage, :all
      else
        can :read, Home
      end
    else
      can :read, Home
    end
  end
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  # belongs_to :user
  # has_many :cart_items, dependent: :destroy
  # validates :total_amount, numericality: { grater_than: 0 }
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :user
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  before_save :set_total

  private

  def set_total
    self.total = item.price * quantity
  end

end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :restaurant
  belongs_to :item_category, class_name: 'ItemCategory'
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items, dependent: :destroy
  validates :name, :description, :price, presence: true
  validates :description, length: { maximum: 500, too_long: '%<count>s characters is the maximum allowed' }            
  validates :price, numericality: { grater_than: 0 }
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/models/item_category.rb
# frozen_string_literal: true

class ItemCategory < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :items, through: :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  before_save :set_sub_total

  private
  def set_sub_total
    self.sub_total=item.price*quantity 
  end
end

app/models/restaurant.rb
# frozen_string_literal: true

class Restaurant < ApplicationRecord
  has_many :items, dependent: :destroy
  validates :name, :description,:address,:phone_1,:phone_2,:minimum_order,:delivery_charge,presence: true
  validates :phone_1, :phone_2, numericality: { only_integer: true }
  validates :phone_1, :phone_2,length: {is: 10}
  validates :description, length: { maximum: 500, too_long: '%<count>s characters is the maximum allowed' }
  validates :minimum_order, numericality: { grater_than: 0 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :validatable
  
  after_validation :normalize_name, on: :create
  after_create :send_welcome_mail
  
  has_many :orders
  has_many :cart_items, dependent: :destroy
  validates :first_name,:last_name,:phone_number, presence: true
  validates :phone_number, numericality: { only_integer: true }
  validates :phone_number,length: {is: 10}
  def normalize_name
    self.first_name = first_name.titleize unless first_name.nil?
  end

  def send_welcome_mail
    UserMailer.welcome_mail(self).deliver_now
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def index
    @cartItems = current_user.cart_items
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController

  def search
    item_id = params[:item_id]
    restaurant_id = params[:restaurant_id]
    @results = if item_id.present? && restaurant_id.present?
                 Restaurant.includes(:items).where(id: restaurant_id, items: { id: item_id })
               elsif item_id.present?
                 Item.includes(:restaurant).where(id: item_id).map(&:restaurant)
               elsif restaurant_id.present?
                 Restaurant.includes(:items).where(id: restaurant_id)
               else
                 Restaurant.includes(:items).all
               end
  end

  def show
    @item = Item.find(params[:item_id]) unless params[:item_id].blank?
  end

end

app/controllers/restaurants_controller.rb
# frozen_string_literal: true

class RestaurantsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    if params[:query].blank?
      @restaurants = Restaurant.all
    else
      @query = params[:query]
      @restaurants = Restaurant.where('lower(name) LIKE ?', "%#{@query}%")
    end
  end

  def search
    @restaurants = Restaurant.where('name Like ?', "%#{params[:query]}%")
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :address, :phone_1, :phone_2)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/buildings_helper.rb
# frozen_string_literal: true

module BuildingsHelper
end

app/helpers/card_helper.rb
# frozen_string_literal: true

module CardHelper
end

app/helpers/cart_items_helper.rb
# frozen_string_literal: true

module CartItemsHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
# frozen_string_literal: true

module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with model: restaurant do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name%>
      <% restaurant.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :description %><br>
      <%= form.text_area :description %><br>
      <% restaurant.errors.full_messages_for(:description).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :address %><br>
      <%= form.text_field :address %><br>
      <% restaurant.errors.full_messages_for(:address).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :phone_1 %><br>
      <%= form.text_field :phone_1 %><br>
      <% restaurant.errors.full_messages_for(:phone_1).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :phone_2 %><br>
      <%= form.text_field :phone_2 %><br>
      <% restaurant.errors.full_messages_for(:phone_2).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Listing Restaurant</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Contact_number_1</th>
      <th>Contact_number_2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.phone_1%></td>
        <td><%= restaurant.phone_2%></td>
        <td><%= link_to "Show", restaurant %>  <%= link_to "Edit", edit_restaurant_path(restaurant) %> <%= link_to "Destroy", restaurant, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<table>
<tr><h1>Welcome to <%= @restaurant.name %></h1></tr>
<tr>
<h3>Address : <%= @restaurant.address%></tr>
<h3>Contact_number_1 : <%= @restaurant.phone_1%></h3>
<h3>Contact_number_2 : <%= @restaurant.phone_2%></h3>
<h3>Minimum_order : <%= @restaurant.minimum_order%></h3>
<h3>Delivery_charge : <%= @restaurant.delivery_charge%></h3>
<h4>Description : </h4><%= @restaurant.description %></h4>
</table>
<p><%= button_to 'Back', restaurants_path , :method => :get%>